#!/usr/bin/env python

from fitr_webapp.app import app

from flask_mongoengine import MongoEngine

from fitr_webapp.models import (
    Users,
    Groups
)


db = MongoEngine(app)

print("Creating everyone group...")
Groups.create_group("everyone")

print("Creating admin group...")
Groups.create_group("admin")


print("Creating ADMIN user...")
admin = Users.create_user(
    username = "admin",
    password = "Scope009870-",
    email = "howzitcallum@gmail.com",
    gender = "Male",
    date_of_birth = "1994-09-16",
    first_name = "Callum",
    surname = "Fleming",
)
print("adding admin to admin group")
admin.add_group("admin")
print(admin)
